-- Ops dashboard DB-backed admin login.
-- This migration intentionally contains only plain SQL so it can run in the
-- Supabase SQL Editor as well as through psql. Create or rotate the first
-- admin separately with public.upsert_ops_admin_user(...), or by passing
-- OPS_ADMIN_LOGIN and OPS_ADMIN_PASSWORD_HASH to backend/scripts/run-required-migrations.ts.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS public.ops_admin_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  login TEXT NOT NULL UNIQUE,
  display_name TEXT,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  last_failed_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ops_admin_users_login_normalized_check CHECK (
    login = lower(btrim(login))
    AND length(login) BETWEEN 3 AND 254
  ),
  CONSTRAINT ops_admin_users_password_hash_format_check CHECK (
    position(':' in password_hash) > 1
  ),
  CONSTRAINT ops_admin_users_role_check CHECK (role IN ('admin')),
  CONSTRAINT ops_admin_users_failed_attempts_nonnegative CHECK (failed_attempts >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ops_admin_users_login_lower
  ON public.ops_admin_users ((lower(login)));

CREATE INDEX IF NOT EXISTS idx_ops_admin_users_active
  ON public.ops_admin_users (active)
  WHERE active = TRUE;

CREATE INDEX IF NOT EXISTS idx_ops_admin_users_locked_until
  ON public.ops_admin_users (locked_until)
  WHERE locked_until IS NOT NULL;

DROP TRIGGER IF EXISTS set_ops_admin_users_updated_at ON public.ops_admin_users;
CREATE TRIGGER set_ops_admin_users_updated_at
  BEFORE UPDATE ON public.ops_admin_users
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.ops_admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ops_admin_users FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_manage_ops_admin_users"
ON public.ops_admin_users;

CREATE POLICY "service_role_manage_ops_admin_users"
ON public.ops_admin_users
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

REVOKE ALL ON TABLE public.ops_admin_users FROM PUBLIC;
DO $$
DECLARE
  role_name text;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON TABLE public.ops_admin_users FROM %I', role_name);
    END IF;
  END LOOP;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.ops_admin_users TO service_role;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.upsert_ops_admin_user(
  p_login TEXT,
  p_password_hash TEXT,
  p_display_name TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id UUID;
  v_login TEXT := lower(btrim(coalesce(p_login, '')));
  v_password_hash TEXT := btrim(coalesce(p_password_hash, ''));
BEGIN
  IF length(v_login) < 3 THEN
    RAISE EXCEPTION 'ops admin login is required';
  END IF;

  IF position(':' in v_password_hash) <= 1 THEN
    RAISE EXCEPTION 'ops admin password_hash must be generated by backend/scripts/hash-ops-admin-password.ts';
  END IF;

  INSERT INTO public.ops_admin_users (
    login,
    display_name,
    password_hash,
    role,
    active,
    failed_attempts,
    locked_until,
    last_failed_at
  )
  VALUES (
    v_login,
    nullif(btrim(coalesce(p_display_name, '')), ''),
    v_password_hash,
    'admin',
    TRUE,
    0,
    NULL,
    NULL
  )
  ON CONFLICT (login) DO UPDATE
  SET
    display_name = COALESCE(EXCLUDED.display_name, public.ops_admin_users.display_name),
    password_hash = EXCLUDED.password_hash,
    active = TRUE,
    failed_attempts = 0,
    locked_until = NULL,
    last_failed_at = NULL,
    updated_at = NOW()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.upsert_ops_admin_user(TEXT, TEXT, TEXT) FROM PUBLIC;
DO $$
DECLARE
  role_name text;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON FUNCTION public.upsert_ops_admin_user(TEXT, TEXT, TEXT) FROM %I', role_name);
    END IF;
  END LOOP;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT EXECUTE ON FUNCTION public.upsert_ops_admin_user(TEXT, TEXT, TEXT) TO service_role;
  END IF;
END $$;
