-- bridge_stellar_wallets: custodial Stellar destination wallets generated for a
-- Bridge customer, keyed by the customer's email. Unlike user_stellar_wallets
-- (which never stores secrets), these wallets are generated by TalkToStellar so
-- the signing key IS stored — encrypted — in the secret vault and referenced by
-- vault_secret_id. This lets the backend create the account on mainnet, add the
-- USDC trustline, and use the wallet as a Bridge → Stellar transfer destination.

BEGIN;

CREATE TABLE IF NOT EXISTS bridge_stellar_wallets (
    id                  BIGSERIAL PRIMARY KEY,
    email               TEXT NOT NULL,                    -- Bridge customer email (lookup key)
    public_key          TEXT UNIQUE NOT NULL,             -- G... Stellar public key
    vault_secret_id     TEXT,                             -- reference into the secret vault (signing key)
    label               TEXT,                             -- optional display name
    is_primary          BOOLEAN NOT NULL DEFAULT false,   -- preferred destination for this email
    is_funded           BOOLEAN NOT NULL DEFAULT false,   -- true once createAccount confirmed on mainnet
    has_usdc_trustline  BOOLEAN NOT NULL DEFAULT false,   -- true once changeTrust(USDC) confirmed
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bridge_stellar_wallets_email      ON bridge_stellar_wallets(email);
CREATE INDEX IF NOT EXISTS idx_bridge_stellar_wallets_public_key ON bridge_stellar_wallets(public_key);

-- ── RLS ───────────────────────────────────────────────────────────────────────
-- Backend connects with SUPABASE_SERVICE_ROLE_KEY (bypasses RLS). Enabling RLS
-- blocks anon/user roles from reading custodial wallet metadata directly.

ALTER TABLE bridge_stellar_wallets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_manage_bridge_stellar_wallets" ON bridge_stellar_wallets;
CREATE POLICY "service_role_manage_bridge_stellar_wallets"
    ON bridge_stellar_wallets
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bridge_stellar_wallets TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.bridge_stellar_wallets_id_seq TO service_role;

COMMIT;
