export function buildCapabilityHelpMessage(): string {
  return [
    "O que posso fazer por você:",
    "",
    "💵 Dinheiro",
    "• Trazer reais via PIX — \"coloca 100 reais\"",
    "• Retirar para seu PIX — \"saca 50 reais pra meu PIX\"",
    "• Receber dólar de banco americano — \"quero trazer dólares\"",
    "",
    "🔄 Converter e trocar",
    "• Converter entre moedas — \"converte 200 reais pra dólar\"",
    "• Trocar tokens diretamente — \"troca 50 XLM por USDC\"",
    "",
    "📈 Aplicações",
    "• Fazer render seu saldo — \"aplica 50 dólares\"",
    "• Ver quanto está rendendo — \"ver meus rendimentos\"",
    "",
    "📤 Enviar e pagar",
    "• Pagar contato salvo — \"manda 20 dólares pra Ana\"",
    "• Criar link de cobrança — \"cria link de 50 dólares\"",
    "",
    "📋 Conta",
    "• Saldo — \"ver meu saldo\"",
    "• Histórico — \"ver histórico\"",
    "• Contatos — \"ver meus contatos\"",
    "• PIN ou acesso — \"trocar meu PIN\"",
    "",
    "Escreva normal, com erros ou abreviações — entendo tudo."
  ].join("\n");
}
